/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppEinstellungenRouteImport } from './routes/_app/einstellungen'
import { Route as AppUmsatzsteuerIndexRouteImport } from './routes/_app/umsatzsteuer/index'
import { Route as AppUmsatzsteuerZeitraumRouteImport } from './routes/_app/umsatzsteuer/$zeitraum'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiProtokollIdRouteImport } from './routes/api/protokoll/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEinstellungenRoute = AppEinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => AppRoute,
} as any)
const AppUmsatzsteuerIndexRoute = AppUmsatzsteuerIndexRouteImport.update({
  id: '/umsatzsteuer/',
  path: '/umsatzsteuer/',
  getParentRoute: () => AppRoute,
} as any)
const AppUmsatzsteuerZeitraumRoute = AppUmsatzsteuerZeitraumRouteImport.update({
  id: '/umsatzsteuer/$zeitraum',
  path: '/umsatzsteuer/$zeitraum',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtokollIdRoute = ApiProtokollIdRouteImport.update({
  id: '/api/protokoll/$id',
  path: '/api/protokoll/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/einstellungen': typeof AppEinstellungenRoute
  '/umsatzsteuer/$zeitraum': typeof AppUmsatzsteuerZeitraumRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/protokoll/$id': typeof ApiProtokollIdRoute
  '/umsatzsteuer/': typeof AppUmsatzsteuerIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/einstellungen': typeof AppEinstellungenRoute
  '/': typeof AppIndexRoute
  '/umsatzsteuer/$zeitraum': typeof AppUmsatzsteuerZeitraumRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/protokoll/$id': typeof ApiProtokollIdRoute
  '/umsatzsteuer': typeof AppUmsatzsteuerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/einstellungen': typeof AppEinstellungenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/umsatzsteuer/$zeitraum': typeof AppUmsatzsteuerZeitraumRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/protokoll/$id': typeof ApiProtokollIdRoute
  '/_app/umsatzsteuer/': typeof AppUmsatzsteuerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/einstellungen'
    | '/umsatzsteuer/$zeitraum'
    | '/api/auth/$'
    | '/api/protokoll/$id'
    | '/umsatzsteuer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/einstellungen'
    | '/'
    | '/umsatzsteuer/$zeitraum'
    | '/api/auth/$'
    | '/api/protokoll/$id'
    | '/umsatzsteuer'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/einstellungen'
    | '/_app/'
    | '/_app/umsatzsteuer/$zeitraum'
    | '/api/auth/$'
    | '/api/protokoll/$id'
    | '/_app/umsatzsteuer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProtokollIdRoute: typeof ApiProtokollIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/einstellungen': {
      id: '/_app/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AppEinstellungenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/umsatzsteuer/': {
      id: '/_app/umsatzsteuer/'
      path: '/umsatzsteuer'
      fullPath: '/umsatzsteuer/'
      preLoaderRoute: typeof AppUmsatzsteuerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/umsatzsteuer/$zeitraum': {
      id: '/_app/umsatzsteuer/$zeitraum'
      path: '/umsatzsteuer/$zeitraum'
      fullPath: '/umsatzsteuer/$zeitraum'
      preLoaderRoute: typeof AppUmsatzsteuerZeitraumRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protokoll/$id': {
      id: '/api/protokoll/$id'
      path: '/api/protokoll/$id'
      fullPath: '/api/protokoll/$id'
      preLoaderRoute: typeof ApiProtokollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppEinstellungenRoute: typeof AppEinstellungenRoute
  AppIndexRoute: typeof AppIndexRoute
  AppUmsatzsteuerZeitraumRoute: typeof AppUmsatzsteuerZeitraumRoute
  AppUmsatzsteuerIndexRoute: typeof AppUmsatzsteuerIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEinstellungenRoute: AppEinstellungenRoute,
  AppIndexRoute: AppIndexRoute,
  AppUmsatzsteuerZeitraumRoute: AppUmsatzsteuerZeitraumRoute,
  AppUmsatzsteuerIndexRoute: AppUmsatzsteuerIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProtokollIdRoute: ApiProtokollIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
