/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAuswertungenRouteImport } from './routes/_app/auswertungen'
import { Route as AppBankRouteImport } from './routes/_app/bank'
import { Route as AppBuchungenRouteImport } from './routes/_app/buchungen'
import { Route as AppEinstellungenRouteImport } from './routes/_app/einstellungen'
import { Route as AppFinanzamtRouteImport } from './routes/_app/finanzamt'
import { Route as AppAnlagenIndexRouteImport } from './routes/_app/anlagen/index'
import { Route as AppAnlagenIdRouteImport } from './routes/_app/anlagen/$id'
import { Route as AppAnlagenNeuRouteImport } from './routes/_app/anlagen/neu'
import { Route as AppArchivIndexRouteImport } from './routes/_app/archiv/index'
import { Route as AppBelegeIndexRouteImport } from './routes/_app/belege/index'
import { Route as AppBelegeIdRouteImport } from './routes/_app/belege/$id'
import { Route as AppJahreserklaerungIndexRouteImport } from './routes/_app/jahreserklaerung/index'
import { Route as AppJahreserklaerungJahrRouteImport } from './routes/_app/jahreserklaerung/$jahr'
import { Route as AppKontakteIndexRouteImport } from './routes/_app/kontakte/index'
import { Route as AppKontakteIdRouteImport } from './routes/_app/kontakte/$id'
import { Route as AppKontakteNeuRouteImport } from './routes/_app/kontakte/neu'
import { Route as AppRechnungenIndexRouteImport } from './routes/_app/rechnungen/index'
import { Route as AppRechnungenIdRouteImport } from './routes/_app/rechnungen/$id'
import { Route as AppRechnungenNeuRouteImport } from './routes/_app/rechnungen/neu'
import { Route as AppUmsatzsteuerIndexRouteImport } from './routes/_app/umsatzsteuer/index'
import { Route as AppUmsatzsteuerZeitraumRouteImport } from './routes/_app/umsatzsteuer/$zeitraum'
import { Route as ApiAltbelegIdRouteImport } from './routes/api/altbeleg/$id'
import { Route as ApiArchivIdRouteImport } from './routes/api/archiv/$id'
import { Route as ApiAuswertungenJahrRouteImport } from './routes/api/auswertungen/$jahr'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBankCallbackRouteImport } from './routes/api/bank/callback'
import { Route as ApiBelegIdRouteImport } from './routes/api/beleg/$id'
import { Route as ApiBelegeTeilenRouteImport } from './routes/api/belege/teilen'
import { Route as ApiExportJahrRouteImport } from './routes/api/export/$jahr'
import { Route as ApiMahnungIdRouteImport } from './routes/api/mahnung/$id'
import { Route as ApiPostfachIdRouteImport } from './routes/api/postfach/$id'
import { Route as ApiProtokollIdRouteImport } from './routes/api/protokoll/$id'
import { Route as AppArchivBelegIdRouteImport } from './routes/_app/archiv/beleg.$id'
import { Route as AppRechnungenMahnwesenIndexRouteImport } from './routes/_app/rechnungen/mahnwesen/index'
import { Route as AppRechnungenMahnwesenIdRouteImport } from './routes/_app/rechnungen/mahnwesen/$id'
import { Route as AppRechnungenWiederkehrendIndexRouteImport } from './routes/_app/rechnungen/wiederkehrend/index'
import { Route as AppRechnungenWiederkehrendIdRouteImport } from './routes/_app/rechnungen/wiederkehrend/$id'
import { Route as AppRechnungenWiederkehrendNeuRouteImport } from './routes/_app/rechnungen/wiederkehrend/neu'
import { Route as ApiRechnungIdDateiRouteImport } from './routes/api/rechnung/$id.$datei'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuswertungenRoute = AppAuswertungenRouteImport.update({
  id: '/auswertungen',
  path: '/auswertungen',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppBuchungenRoute = AppBuchungenRouteImport.update({
  id: '/buchungen',
  path: '/buchungen',
  getParentRoute: () => AppRoute,
} as any)
const AppEinstellungenRoute = AppEinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzamtRoute = AppFinanzamtRouteImport.update({
  id: '/finanzamt',
  path: '/finanzamt',
  getParentRoute: () => AppRoute,
} as any)
const AppAnlagenIndexRoute = AppAnlagenIndexRouteImport.update({
  id: '/anlagen/',
  path: '/anlagen/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnlagenIdRoute = AppAnlagenIdRouteImport.update({
  id: '/anlagen/$id',
  path: '/anlagen/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAnlagenNeuRoute = AppAnlagenNeuRouteImport.update({
  id: '/anlagen/neu',
  path: '/anlagen/neu',
  getParentRoute: () => AppRoute,
} as any)
const AppArchivIndexRoute = AppArchivIndexRouteImport.update({
  id: '/archiv/',
  path: '/archiv/',
  getParentRoute: () => AppRoute,
} as any)
const AppBelegeIndexRoute = AppBelegeIndexRouteImport.update({
  id: '/belege/',
  path: '/belege/',
  getParentRoute: () => AppRoute,
} as any)
const AppBelegeIdRoute = AppBelegeIdRouteImport.update({
  id: '/belege/$id',
  path: '/belege/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppJahreserklaerungIndexRoute =
  AppJahreserklaerungIndexRouteImport.update({
    id: '/jahreserklaerung/',
    path: '/jahreserklaerung/',
    getParentRoute: () => AppRoute,
  } as any)
const AppJahreserklaerungJahrRoute = AppJahreserklaerungJahrRouteImport.update({
  id: '/jahreserklaerung/$jahr',
  path: '/jahreserklaerung/$jahr',
  getParentRoute: () => AppRoute,
} as any)
const AppKontakteIndexRoute = AppKontakteIndexRouteImport.update({
  id: '/kontakte/',
  path: '/kontakte/',
  getParentRoute: () => AppRoute,
} as any)
const AppKontakteIdRoute = AppKontakteIdRouteImport.update({
  id: '/kontakte/$id',
  path: '/kontakte/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppKontakteNeuRoute = AppKontakteNeuRouteImport.update({
  id: '/kontakte/neu',
  path: '/kontakte/neu',
  getParentRoute: () => AppRoute,
} as any)
const AppRechnungenIndexRoute = AppRechnungenIndexRouteImport.update({
  id: '/rechnungen/',
  path: '/rechnungen/',
  getParentRoute: () => AppRoute,
} as any)
const AppRechnungenIdRoute = AppRechnungenIdRouteImport.update({
  id: '/rechnungen/$id',
  path: '/rechnungen/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRechnungenNeuRoute = AppRechnungenNeuRouteImport.update({
  id: '/rechnungen/neu',
  path: '/rechnungen/neu',
  getParentRoute: () => AppRoute,
} as any)
const AppUmsatzsteuerIndexRoute = AppUmsatzsteuerIndexRouteImport.update({
  id: '/umsatzsteuer/',
  path: '/umsatzsteuer/',
  getParentRoute: () => AppRoute,
} as any)
const AppUmsatzsteuerZeitraumRoute = AppUmsatzsteuerZeitraumRouteImport.update({
  id: '/umsatzsteuer/$zeitraum',
  path: '/umsatzsteuer/$zeitraum',
  getParentRoute: () => AppRoute,
} as any)
const ApiAltbelegIdRoute = ApiAltbelegIdRouteImport.update({
  id: '/api/altbeleg/$id',
  path: '/api/altbeleg/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchivIdRoute = ApiArchivIdRouteImport.update({
  id: '/api/archiv/$id',
  path: '/api/archiv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuswertungenJahrRoute = ApiAuswertungenJahrRouteImport.update({
  id: '/api/auswertungen/$jahr',
  path: '/api/auswertungen/$jahr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBankCallbackRoute = ApiBankCallbackRouteImport.update({
  id: '/api/bank/callback',
  path: '/api/bank/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBelegIdRoute = ApiBelegIdRouteImport.update({
  id: '/api/beleg/$id',
  path: '/api/beleg/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBelegeTeilenRoute = ApiBelegeTeilenRouteImport.update({
  id: '/api/belege/teilen',
  path: '/api/belege/teilen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportJahrRoute = ApiExportJahrRouteImport.update({
  id: '/api/export/$jahr',
  path: '/api/export/$jahr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMahnungIdRoute = ApiMahnungIdRouteImport.update({
  id: '/api/mahnung/$id',
  path: '/api/mahnung/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostfachIdRoute = ApiPostfachIdRouteImport.update({
  id: '/api/postfach/$id',
  path: '/api/postfach/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtokollIdRoute = ApiProtokollIdRouteImport.update({
  id: '/api/protokoll/$id',
  path: '/api/protokoll/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppArchivBelegIdRoute = AppArchivBelegIdRouteImport.update({
  id: '/archiv/beleg/$id',
  path: '/archiv/beleg/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRechnungenMahnwesenIndexRoute =
  AppRechnungenMahnwesenIndexRouteImport.update({
    id: '/rechnungen/mahnwesen/',
    path: '/rechnungen/mahnwesen/',
    getParentRoute: () => AppRoute,
  } as any)
const AppRechnungenMahnwesenIdRoute =
  AppRechnungenMahnwesenIdRouteImport.update({
    id: '/rechnungen/mahnwesen/$id',
    path: '/rechnungen/mahnwesen/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppRechnungenWiederkehrendIndexRoute =
  AppRechnungenWiederkehrendIndexRouteImport.update({
    id: '/rechnungen/wiederkehrend/',
    path: '/rechnungen/wiederkehrend/',
    getParentRoute: () => AppRoute,
  } as any)
const AppRechnungenWiederkehrendIdRoute =
  AppRechnungenWiederkehrendIdRouteImport.update({
    id: '/rechnungen/wiederkehrend/$id',
    path: '/rechnungen/wiederkehrend/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppRechnungenWiederkehrendNeuRoute =
  AppRechnungenWiederkehrendNeuRouteImport.update({
    id: '/rechnungen/wiederkehrend/neu',
    path: '/rechnungen/wiederkehrend/neu',
    getParentRoute: () => AppRoute,
  } as any)
const ApiRechnungIdDateiRoute = ApiRechnungIdDateiRouteImport.update({
  id: '/api/rechnung/$id/$datei',
  path: '/api/rechnung/$id/$datei',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/auswertungen': typeof AppAuswertungenRoute
  '/bank': typeof AppBankRoute
  '/buchungen': typeof AppBuchungenRoute
  '/einstellungen': typeof AppEinstellungenRoute
  '/finanzamt': typeof AppFinanzamtRoute
  '/anlagen/$id': typeof AppAnlagenIdRoute
  '/anlagen/neu': typeof AppAnlagenNeuRoute
  '/belege/$id': typeof AppBelegeIdRoute
  '/jahreserklaerung/$jahr': typeof AppJahreserklaerungJahrRoute
  '/kontakte/$id': typeof AppKontakteIdRoute
  '/kontakte/neu': typeof AppKontakteNeuRoute
  '/rechnungen/$id': typeof AppRechnungenIdRoute
  '/rechnungen/neu': typeof AppRechnungenNeuRoute
  '/umsatzsteuer/$zeitraum': typeof AppUmsatzsteuerZeitraumRoute
  '/api/altbeleg/$id': typeof ApiAltbelegIdRoute
  '/api/archiv/$id': typeof ApiArchivIdRoute
  '/api/auswertungen/$jahr': typeof ApiAuswertungenJahrRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bank/callback': typeof ApiBankCallbackRoute
  '/api/beleg/$id': typeof ApiBelegIdRoute
  '/api/belege/teilen': typeof ApiBelegeTeilenRoute
  '/api/export/$jahr': typeof ApiExportJahrRoute
  '/api/mahnung/$id': typeof ApiMahnungIdRoute
  '/api/postfach/$id': typeof ApiPostfachIdRoute
  '/api/protokoll/$id': typeof ApiProtokollIdRoute
  '/anlagen/': typeof AppAnlagenIndexRoute
  '/archiv/': typeof AppArchivIndexRoute
  '/belege/': typeof AppBelegeIndexRoute
  '/jahreserklaerung/': typeof AppJahreserklaerungIndexRoute
  '/kontakte/': typeof AppKontakteIndexRoute
  '/rechnungen/': typeof AppRechnungenIndexRoute
  '/umsatzsteuer/': typeof AppUmsatzsteuerIndexRoute
  '/archiv/beleg/$id': typeof AppArchivBelegIdRoute
  '/rechnungen/mahnwesen/$id': typeof AppRechnungenMahnwesenIdRoute
  '/rechnungen/wiederkehrend/$id': typeof AppRechnungenWiederkehrendIdRoute
  '/rechnungen/wiederkehrend/neu': typeof AppRechnungenWiederkehrendNeuRoute
  '/api/rechnung/$id/$datei': typeof ApiRechnungIdDateiRoute
  '/rechnungen/mahnwesen/': typeof AppRechnungenMahnwesenIndexRoute
  '/rechnungen/wiederkehrend/': typeof AppRechnungenWiederkehrendIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/auswertungen': typeof AppAuswertungenRoute
  '/bank': typeof AppBankRoute
  '/buchungen': typeof AppBuchungenRoute
  '/einstellungen': typeof AppEinstellungenRoute
  '/finanzamt': typeof AppFinanzamtRoute
  '/': typeof AppIndexRoute
  '/anlagen/$id': typeof AppAnlagenIdRoute
  '/anlagen/neu': typeof AppAnlagenNeuRoute
  '/belege/$id': typeof AppBelegeIdRoute
  '/jahreserklaerung/$jahr': typeof AppJahreserklaerungJahrRoute
  '/kontakte/$id': typeof AppKontakteIdRoute
  '/kontakte/neu': typeof AppKontakteNeuRoute
  '/rechnungen/$id': typeof AppRechnungenIdRoute
  '/rechnungen/neu': typeof AppRechnungenNeuRoute
  '/umsatzsteuer/$zeitraum': typeof AppUmsatzsteuerZeitraumRoute
  '/api/altbeleg/$id': typeof ApiAltbelegIdRoute
  '/api/archiv/$id': typeof ApiArchivIdRoute
  '/api/auswertungen/$jahr': typeof ApiAuswertungenJahrRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bank/callback': typeof ApiBankCallbackRoute
  '/api/beleg/$id': typeof ApiBelegIdRoute
  '/api/belege/teilen': typeof ApiBelegeTeilenRoute
  '/api/export/$jahr': typeof ApiExportJahrRoute
  '/api/mahnung/$id': typeof ApiMahnungIdRoute
  '/api/postfach/$id': typeof ApiPostfachIdRoute
  '/api/protokoll/$id': typeof ApiProtokollIdRoute
  '/anlagen': typeof AppAnlagenIndexRoute
  '/archiv': typeof AppArchivIndexRoute
  '/belege': typeof AppBelegeIndexRoute
  '/jahreserklaerung': typeof AppJahreserklaerungIndexRoute
  '/kontakte': typeof AppKontakteIndexRoute
  '/rechnungen': typeof AppRechnungenIndexRoute
  '/umsatzsteuer': typeof AppUmsatzsteuerIndexRoute
  '/archiv/beleg/$id': typeof AppArchivBelegIdRoute
  '/rechnungen/mahnwesen/$id': typeof AppRechnungenMahnwesenIdRoute
  '/rechnungen/wiederkehrend/$id': typeof AppRechnungenWiederkehrendIdRoute
  '/rechnungen/wiederkehrend/neu': typeof AppRechnungenWiederkehrendNeuRoute
  '/api/rechnung/$id/$datei': typeof ApiRechnungIdDateiRoute
  '/rechnungen/mahnwesen': typeof AppRechnungenMahnwesenIndexRoute
  '/rechnungen/wiederkehrend': typeof AppRechnungenWiederkehrendIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/auswertungen': typeof AppAuswertungenRoute
  '/_app/bank': typeof AppBankRoute
  '/_app/buchungen': typeof AppBuchungenRoute
  '/_app/einstellungen': typeof AppEinstellungenRoute
  '/_app/finanzamt': typeof AppFinanzamtRoute
  '/_app/': typeof AppIndexRoute
  '/_app/anlagen/$id': typeof AppAnlagenIdRoute
  '/_app/anlagen/neu': typeof AppAnlagenNeuRoute
  '/_app/belege/$id': typeof AppBelegeIdRoute
  '/_app/jahreserklaerung/$jahr': typeof AppJahreserklaerungJahrRoute
  '/_app/kontakte/$id': typeof AppKontakteIdRoute
  '/_app/kontakte/neu': typeof AppKontakteNeuRoute
  '/_app/rechnungen/$id': typeof AppRechnungenIdRoute
  '/_app/rechnungen/neu': typeof AppRechnungenNeuRoute
  '/_app/umsatzsteuer/$zeitraum': typeof AppUmsatzsteuerZeitraumRoute
  '/api/altbeleg/$id': typeof ApiAltbelegIdRoute
  '/api/archiv/$id': typeof ApiArchivIdRoute
  '/api/auswertungen/$jahr': typeof ApiAuswertungenJahrRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bank/callback': typeof ApiBankCallbackRoute
  '/api/beleg/$id': typeof ApiBelegIdRoute
  '/api/belege/teilen': typeof ApiBelegeTeilenRoute
  '/api/export/$jahr': typeof ApiExportJahrRoute
  '/api/mahnung/$id': typeof ApiMahnungIdRoute
  '/api/postfach/$id': typeof ApiPostfachIdRoute
  '/api/protokoll/$id': typeof ApiProtokollIdRoute
  '/_app/anlagen/': typeof AppAnlagenIndexRoute
  '/_app/archiv/': typeof AppArchivIndexRoute
  '/_app/belege/': typeof AppBelegeIndexRoute
  '/_app/jahreserklaerung/': typeof AppJahreserklaerungIndexRoute
  '/_app/kontakte/': typeof AppKontakteIndexRoute
  '/_app/rechnungen/': typeof AppRechnungenIndexRoute
  '/_app/umsatzsteuer/': typeof AppUmsatzsteuerIndexRoute
  '/_app/archiv/beleg/$id': typeof AppArchivBelegIdRoute
  '/_app/rechnungen/mahnwesen/$id': typeof AppRechnungenMahnwesenIdRoute
  '/_app/rechnungen/wiederkehrend/$id': typeof AppRechnungenWiederkehrendIdRoute
  '/_app/rechnungen/wiederkehrend/neu': typeof AppRechnungenWiederkehrendNeuRoute
  '/api/rechnung/$id/$datei': typeof ApiRechnungIdDateiRoute
  '/_app/rechnungen/mahnwesen/': typeof AppRechnungenMahnwesenIndexRoute
  '/_app/rechnungen/wiederkehrend/': typeof AppRechnungenWiederkehrendIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/auswertungen'
    | '/bank'
    | '/buchungen'
    | '/einstellungen'
    | '/finanzamt'
    | '/anlagen/$id'
    | '/anlagen/neu'
    | '/belege/$id'
    | '/jahreserklaerung/$jahr'
    | '/kontakte/$id'
    | '/kontakte/neu'
    | '/rechnungen/$id'
    | '/rechnungen/neu'
    | '/umsatzsteuer/$zeitraum'
    | '/api/altbeleg/$id'
    | '/api/archiv/$id'
    | '/api/auswertungen/$jahr'
    | '/api/auth/$'
    | '/api/bank/callback'
    | '/api/beleg/$id'
    | '/api/belege/teilen'
    | '/api/export/$jahr'
    | '/api/mahnung/$id'
    | '/api/postfach/$id'
    | '/api/protokoll/$id'
    | '/anlagen/'
    | '/archiv/'
    | '/belege/'
    | '/jahreserklaerung/'
    | '/kontakte/'
    | '/rechnungen/'
    | '/umsatzsteuer/'
    | '/archiv/beleg/$id'
    | '/rechnungen/mahnwesen/$id'
    | '/rechnungen/wiederkehrend/$id'
    | '/rechnungen/wiederkehrend/neu'
    | '/api/rechnung/$id/$datei'
    | '/rechnungen/mahnwesen/'
    | '/rechnungen/wiederkehrend/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/auswertungen'
    | '/bank'
    | '/buchungen'
    | '/einstellungen'
    | '/finanzamt'
    | '/'
    | '/anlagen/$id'
    | '/anlagen/neu'
    | '/belege/$id'
    | '/jahreserklaerung/$jahr'
    | '/kontakte/$id'
    | '/kontakte/neu'
    | '/rechnungen/$id'
    | '/rechnungen/neu'
    | '/umsatzsteuer/$zeitraum'
    | '/api/altbeleg/$id'
    | '/api/archiv/$id'
    | '/api/auswertungen/$jahr'
    | '/api/auth/$'
    | '/api/bank/callback'
    | '/api/beleg/$id'
    | '/api/belege/teilen'
    | '/api/export/$jahr'
    | '/api/mahnung/$id'
    | '/api/postfach/$id'
    | '/api/protokoll/$id'
    | '/anlagen'
    | '/archiv'
    | '/belege'
    | '/jahreserklaerung'
    | '/kontakte'
    | '/rechnungen'
    | '/umsatzsteuer'
    | '/archiv/beleg/$id'
    | '/rechnungen/mahnwesen/$id'
    | '/rechnungen/wiederkehrend/$id'
    | '/rechnungen/wiederkehrend/neu'
    | '/api/rechnung/$id/$datei'
    | '/rechnungen/mahnwesen'
    | '/rechnungen/wiederkehrend'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/auswertungen'
    | '/_app/bank'
    | '/_app/buchungen'
    | '/_app/einstellungen'
    | '/_app/finanzamt'
    | '/_app/'
    | '/_app/anlagen/$id'
    | '/_app/anlagen/neu'
    | '/_app/belege/$id'
    | '/_app/jahreserklaerung/$jahr'
    | '/_app/kontakte/$id'
    | '/_app/kontakte/neu'
    | '/_app/rechnungen/$id'
    | '/_app/rechnungen/neu'
    | '/_app/umsatzsteuer/$zeitraum'
    | '/api/altbeleg/$id'
    | '/api/archiv/$id'
    | '/api/auswertungen/$jahr'
    | '/api/auth/$'
    | '/api/bank/callback'
    | '/api/beleg/$id'
    | '/api/belege/teilen'
    | '/api/export/$jahr'
    | '/api/mahnung/$id'
    | '/api/postfach/$id'
    | '/api/protokoll/$id'
    | '/_app/anlagen/'
    | '/_app/archiv/'
    | '/_app/belege/'
    | '/_app/jahreserklaerung/'
    | '/_app/kontakte/'
    | '/_app/rechnungen/'
    | '/_app/umsatzsteuer/'
    | '/_app/archiv/beleg/$id'
    | '/_app/rechnungen/mahnwesen/$id'
    | '/_app/rechnungen/wiederkehrend/$id'
    | '/_app/rechnungen/wiederkehrend/neu'
    | '/api/rechnung/$id/$datei'
    | '/_app/rechnungen/mahnwesen/'
    | '/_app/rechnungen/wiederkehrend/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiAltbelegIdRoute: typeof ApiAltbelegIdRoute
  ApiArchivIdRoute: typeof ApiArchivIdRoute
  ApiAuswertungenJahrRoute: typeof ApiAuswertungenJahrRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBankCallbackRoute: typeof ApiBankCallbackRoute
  ApiBelegIdRoute: typeof ApiBelegIdRoute
  ApiBelegeTeilenRoute: typeof ApiBelegeTeilenRoute
  ApiExportJahrRoute: typeof ApiExportJahrRoute
  ApiMahnungIdRoute: typeof ApiMahnungIdRoute
  ApiPostfachIdRoute: typeof ApiPostfachIdRoute
  ApiProtokollIdRoute: typeof ApiProtokollIdRoute
  ApiRechnungIdDateiRoute: typeof ApiRechnungIdDateiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auswertungen': {
      id: '/_app/auswertungen'
      path: '/auswertungen'
      fullPath: '/auswertungen'
      preLoaderRoute: typeof AppAuswertungenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank': {
      id: '/_app/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buchungen': {
      id: '/_app/buchungen'
      path: '/buchungen'
      fullPath: '/buchungen'
      preLoaderRoute: typeof AppBuchungenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/einstellungen': {
      id: '/_app/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AppEinstellungenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finanzamt': {
      id: '/_app/finanzamt'
      path: '/finanzamt'
      fullPath: '/finanzamt'
      preLoaderRoute: typeof AppFinanzamtRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anlagen/': {
      id: '/_app/anlagen/'
      path: '/anlagen'
      fullPath: '/anlagen/'
      preLoaderRoute: typeof AppAnlagenIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anlagen/$id': {
      id: '/_app/anlagen/$id'
      path: '/anlagen/$id'
      fullPath: '/anlagen/$id'
      preLoaderRoute: typeof AppAnlagenIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anlagen/neu': {
      id: '/_app/anlagen/neu'
      path: '/anlagen/neu'
      fullPath: '/anlagen/neu'
      preLoaderRoute: typeof AppAnlagenNeuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archiv/': {
      id: '/_app/archiv/'
      path: '/archiv'
      fullPath: '/archiv/'
      preLoaderRoute: typeof AppArchivIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/belege/': {
      id: '/_app/belege/'
      path: '/belege'
      fullPath: '/belege/'
      preLoaderRoute: typeof AppBelegeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/belege/$id': {
      id: '/_app/belege/$id'
      path: '/belege/$id'
      fullPath: '/belege/$id'
      preLoaderRoute: typeof AppBelegeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jahreserklaerung/': {
      id: '/_app/jahreserklaerung/'
      path: '/jahreserklaerung'
      fullPath: '/jahreserklaerung/'
      preLoaderRoute: typeof AppJahreserklaerungIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jahreserklaerung/$jahr': {
      id: '/_app/jahreserklaerung/$jahr'
      path: '/jahreserklaerung/$jahr'
      fullPath: '/jahreserklaerung/$jahr'
      preLoaderRoute: typeof AppJahreserklaerungJahrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kontakte/': {
      id: '/_app/kontakte/'
      path: '/kontakte'
      fullPath: '/kontakte/'
      preLoaderRoute: typeof AppKontakteIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kontakte/$id': {
      id: '/_app/kontakte/$id'
      path: '/kontakte/$id'
      fullPath: '/kontakte/$id'
      preLoaderRoute: typeof AppKontakteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kontakte/neu': {
      id: '/_app/kontakte/neu'
      path: '/kontakte/neu'
      fullPath: '/kontakte/neu'
      preLoaderRoute: typeof AppKontakteNeuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rechnungen/': {
      id: '/_app/rechnungen/'
      path: '/rechnungen'
      fullPath: '/rechnungen/'
      preLoaderRoute: typeof AppRechnungenIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rechnungen/$id': {
      id: '/_app/rechnungen/$id'
      path: '/rechnungen/$id'
      fullPath: '/rechnungen/$id'
      preLoaderRoute: typeof AppRechnungenIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rechnungen/neu': {
      id: '/_app/rechnungen/neu'
      path: '/rechnungen/neu'
      fullPath: '/rechnungen/neu'
      preLoaderRoute: typeof AppRechnungenNeuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/umsatzsteuer/': {
      id: '/_app/umsatzsteuer/'
      path: '/umsatzsteuer'
      fullPath: '/umsatzsteuer/'
      preLoaderRoute: typeof AppUmsatzsteuerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/umsatzsteuer/$zeitraum': {
      id: '/_app/umsatzsteuer/$zeitraum'
      path: '/umsatzsteuer/$zeitraum'
      fullPath: '/umsatzsteuer/$zeitraum'
      preLoaderRoute: typeof AppUmsatzsteuerZeitraumRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/altbeleg/$id': {
      id: '/api/altbeleg/$id'
      path: '/api/altbeleg/$id'
      fullPath: '/api/altbeleg/$id'
      preLoaderRoute: typeof ApiAltbelegIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archiv/$id': {
      id: '/api/archiv/$id'
      path: '/api/archiv/$id'
      fullPath: '/api/archiv/$id'
      preLoaderRoute: typeof ApiArchivIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auswertungen/$jahr': {
      id: '/api/auswertungen/$jahr'
      path: '/api/auswertungen/$jahr'
      fullPath: '/api/auswertungen/$jahr'
      preLoaderRoute: typeof ApiAuswertungenJahrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bank/callback': {
      id: '/api/bank/callback'
      path: '/api/bank/callback'
      fullPath: '/api/bank/callback'
      preLoaderRoute: typeof ApiBankCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beleg/$id': {
      id: '/api/beleg/$id'
      path: '/api/beleg/$id'
      fullPath: '/api/beleg/$id'
      preLoaderRoute: typeof ApiBelegIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/belege/teilen': {
      id: '/api/belege/teilen'
      path: '/api/belege/teilen'
      fullPath: '/api/belege/teilen'
      preLoaderRoute: typeof ApiBelegeTeilenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/$jahr': {
      id: '/api/export/$jahr'
      path: '/api/export/$jahr'
      fullPath: '/api/export/$jahr'
      preLoaderRoute: typeof ApiExportJahrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mahnung/$id': {
      id: '/api/mahnung/$id'
      path: '/api/mahnung/$id'
      fullPath: '/api/mahnung/$id'
      preLoaderRoute: typeof ApiMahnungIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/postfach/$id': {
      id: '/api/postfach/$id'
      path: '/api/postfach/$id'
      fullPath: '/api/postfach/$id'
      preLoaderRoute: typeof ApiPostfachIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protokoll/$id': {
      id: '/api/protokoll/$id'
      path: '/api/protokoll/$id'
      fullPath: '/api/protokoll/$id'
      preLoaderRoute: typeof ApiProtokollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/archiv/beleg/$id': {
      id: '/_app/archiv/beleg/$id'
      path: '/archiv/beleg/$id'
      fullPath: '/archiv/beleg/$id'
      preLoaderRoute: typeof AppArchivBelegIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rechnungen/mahnwesen/': {
      id: '/_app/rechnungen/mahnwesen/'
      path: '/rechnungen/mahnwesen'
      fullPath: '/rechnungen/mahnwesen/'
      preLoaderRoute: typeof AppRechnungenMahnwesenIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rechnungen/mahnwesen/$id': {
      id: '/_app/rechnungen/mahnwesen/$id'
      path: '/rechnungen/mahnwesen/$id'
      fullPath: '/rechnungen/mahnwesen/$id'
      preLoaderRoute: typeof AppRechnungenMahnwesenIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rechnungen/wiederkehrend/': {
      id: '/_app/rechnungen/wiederkehrend/'
      path: '/rechnungen/wiederkehrend'
      fullPath: '/rechnungen/wiederkehrend/'
      preLoaderRoute: typeof AppRechnungenWiederkehrendIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rechnungen/wiederkehrend/$id': {
      id: '/_app/rechnungen/wiederkehrend/$id'
      path: '/rechnungen/wiederkehrend/$id'
      fullPath: '/rechnungen/wiederkehrend/$id'
      preLoaderRoute: typeof AppRechnungenWiederkehrendIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rechnungen/wiederkehrend/neu': {
      id: '/_app/rechnungen/wiederkehrend/neu'
      path: '/rechnungen/wiederkehrend/neu'
      fullPath: '/rechnungen/wiederkehrend/neu'
      preLoaderRoute: typeof AppRechnungenWiederkehrendNeuRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/rechnung/$id/$datei': {
      id: '/api/rechnung/$id/$datei'
      path: '/api/rechnung/$id/$datei'
      fullPath: '/api/rechnung/$id/$datei'
      preLoaderRoute: typeof ApiRechnungIdDateiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAuswertungenRoute: typeof AppAuswertungenRoute
  AppBankRoute: typeof AppBankRoute
  AppBuchungenRoute: typeof AppBuchungenRoute
  AppEinstellungenRoute: typeof AppEinstellungenRoute
  AppFinanzamtRoute: typeof AppFinanzamtRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAnlagenIdRoute: typeof AppAnlagenIdRoute
  AppAnlagenNeuRoute: typeof AppAnlagenNeuRoute
  AppBelegeIdRoute: typeof AppBelegeIdRoute
  AppJahreserklaerungJahrRoute: typeof AppJahreserklaerungJahrRoute
  AppKontakteIdRoute: typeof AppKontakteIdRoute
  AppKontakteNeuRoute: typeof AppKontakteNeuRoute
  AppRechnungenIdRoute: typeof AppRechnungenIdRoute
  AppRechnungenNeuRoute: typeof AppRechnungenNeuRoute
  AppUmsatzsteuerZeitraumRoute: typeof AppUmsatzsteuerZeitraumRoute
  AppAnlagenIndexRoute: typeof AppAnlagenIndexRoute
  AppArchivIndexRoute: typeof AppArchivIndexRoute
  AppBelegeIndexRoute: typeof AppBelegeIndexRoute
  AppJahreserklaerungIndexRoute: typeof AppJahreserklaerungIndexRoute
  AppKontakteIndexRoute: typeof AppKontakteIndexRoute
  AppRechnungenIndexRoute: typeof AppRechnungenIndexRoute
  AppUmsatzsteuerIndexRoute: typeof AppUmsatzsteuerIndexRoute
  AppArchivBelegIdRoute: typeof AppArchivBelegIdRoute
  AppRechnungenMahnwesenIdRoute: typeof AppRechnungenMahnwesenIdRoute
  AppRechnungenWiederkehrendIdRoute: typeof AppRechnungenWiederkehrendIdRoute
  AppRechnungenWiederkehrendNeuRoute: typeof AppRechnungenWiederkehrendNeuRoute
  AppRechnungenMahnwesenIndexRoute: typeof AppRechnungenMahnwesenIndexRoute
  AppRechnungenWiederkehrendIndexRoute: typeof AppRechnungenWiederkehrendIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuswertungenRoute: AppAuswertungenRoute,
  AppBankRoute: AppBankRoute,
  AppBuchungenRoute: AppBuchungenRoute,
  AppEinstellungenRoute: AppEinstellungenRoute,
  AppFinanzamtRoute: AppFinanzamtRoute,
  AppIndexRoute: AppIndexRoute,
  AppAnlagenIdRoute: AppAnlagenIdRoute,
  AppAnlagenNeuRoute: AppAnlagenNeuRoute,
  AppBelegeIdRoute: AppBelegeIdRoute,
  AppJahreserklaerungJahrRoute: AppJahreserklaerungJahrRoute,
  AppKontakteIdRoute: AppKontakteIdRoute,
  AppKontakteNeuRoute: AppKontakteNeuRoute,
  AppRechnungenIdRoute: AppRechnungenIdRoute,
  AppRechnungenNeuRoute: AppRechnungenNeuRoute,
  AppUmsatzsteuerZeitraumRoute: AppUmsatzsteuerZeitraumRoute,
  AppAnlagenIndexRoute: AppAnlagenIndexRoute,
  AppArchivIndexRoute: AppArchivIndexRoute,
  AppBelegeIndexRoute: AppBelegeIndexRoute,
  AppJahreserklaerungIndexRoute: AppJahreserklaerungIndexRoute,
  AppKontakteIndexRoute: AppKontakteIndexRoute,
  AppRechnungenIndexRoute: AppRechnungenIndexRoute,
  AppUmsatzsteuerIndexRoute: AppUmsatzsteuerIndexRoute,
  AppArchivBelegIdRoute: AppArchivBelegIdRoute,
  AppRechnungenMahnwesenIdRoute: AppRechnungenMahnwesenIdRoute,
  AppRechnungenWiederkehrendIdRoute: AppRechnungenWiederkehrendIdRoute,
  AppRechnungenWiederkehrendNeuRoute: AppRechnungenWiederkehrendNeuRoute,
  AppRechnungenMahnwesenIndexRoute: AppRechnungenMahnwesenIndexRoute,
  AppRechnungenWiederkehrendIndexRoute: AppRechnungenWiederkehrendIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiAltbelegIdRoute: ApiAltbelegIdRoute,
  ApiArchivIdRoute: ApiArchivIdRoute,
  ApiAuswertungenJahrRoute: ApiAuswertungenJahrRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBankCallbackRoute: ApiBankCallbackRoute,
  ApiBelegIdRoute: ApiBelegIdRoute,
  ApiBelegeTeilenRoute: ApiBelegeTeilenRoute,
  ApiExportJahrRoute: ApiExportJahrRoute,
  ApiMahnungIdRoute: ApiMahnungIdRoute,
  ApiPostfachIdRoute: ApiPostfachIdRoute,
  ApiProtokollIdRoute: ApiProtokollIdRoute,
  ApiRechnungIdDateiRoute: ApiRechnungIdDateiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
