/** Religionsschlüssel laut ELSTER (Zeile 7/8 des Hauptvordrucks), wie bei viking */
export const RELIGIONEN: { code: string; label: string }[] = [
  { code: "11", label: "Keine (nicht kirchensteuerpflichtig)" },
  { code: "02", label: "Evangelisch" },
  { code: "03", label: "Römisch-katholisch" },
  { code: "04", label: "Altkatholisch" },
  { code: "05", label: "Evangelisch-reformiert" },
  { code: "07", label: "Französisch-reformiert" },
  { code: "12", label: "Israelitische Religionsgemeinschaft Württemberg" },
  { code: "13", label: "Freireligiöse Landesgemeinde Baden" },
  { code: "14", label: "Freireligiöse Landesgemeinde Pfalz" },
  { code: "15", label: "Freireligiöse Gemeinde Mainz" },
  { code: "16", label: "Freie Religionsgemeinschaft Alzey" },
  { code: "17", label: "Freireligiöse Gemeinde Offenbach" },
  { code: "18", label: "Jüdische Gemeinde Frankfurt (Hessen)" },
  { code: "19", label: "Jüdische Gemeinden Hessen" },
  { code: "20", label: "Ev.-ref. Kirche Bückeburg" },
  { code: "21", label: "Ev.-ref. Kirche Stadthagen" },
  { code: "24", label: "Jüdische Gemeinde Hamburg" },
  { code: "25", label: "Israelitische Religionsgemeinschaft Baden" },
  { code: "26", label: "Landesverband isr. Kultusgemeinden Bayern" },
  { code: "27", label: "Jüdische Kultusgemeinden Bad Kreuznach/Koblenz" },
  { code: "28", label: "Israelitisch (Saarland)" },
  { code: "29", label: "Nordrhein-Westfalen: Israelitisch" },
  { code: "10", label: "Sonstige" },
];
